### ISSUE TITLE
レイアウトの追加について

### ISSUE THREAD

**Issue by noritora** [ya-s-u/NewsPaperGenerator#33]
レイアウトを私自身で追加できるようにやり方を教えていただきたいです．

**Comment by ya-s-u** [comment]
コードの修正が必要

**Comment by ya-s-u** [comment]
レイアウトを追加しやすいようにコードを改善する

**Comment by pokohide** [comment]
現状レイアウトは、cssで指定しています。
例えば初期のレイアウトだと、

`````` css
/* タイプ１ */
.articles.layout1 li:nth-child(1) {
  left: calc(100% / 12 * 0)!important;
  top: calc(100% / 12 * 0)!important;
  width: calc(100% / 12 * 12);
  height: calc(100% / 12 * 4);
}
.articles.layout1 li:nth-child(2) {
  left: calc(100% / 12 * 0)!important;
  top: calc(100% / 12 * 9)!important;
  width: calc(100% / 12 * 7);
  height: calc(100% / 12 * 3);
}
.articles.layout1 li:nth-child(3) {
  left: calc(100% / 12 * 7)!important;
  top: calc(100% / 12 * 8)!important;
  width: calc(100% / 12 * 5);
  height: calc(100% / 12 * 4);
}
.articles.layout1 li:nth-child(4) {
  left: calc(100% / 12 * 0)!important;
  top: calc(100% / 12 * 4)!important;
  width: calc(100% / 12 * 4);
  height: calc(100% / 12 * 5);
}
.articles.layout1 li:nth-child(5) {
  left: calc(100% / 12 * 7)!important;
  top: calc(100% / 12 * 4)!important;
  width: calc(100% / 12 * 5);
  height: calc(100% / 12 * 4);
}
.articles.layout1 li:nth-child(6) {
  left: calc(100% / 12 * 4)!important;
  top: calc(100% / 12 * 4)!important;
  width: calc(100% / 12 * 3);

```
``````
